# NOTE: update this with your service name
service: designed-bot

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    WEBHOOK_URL: ${env:WEBHOOK_URL}
    API_URL: ${env:API_URL}

custom:
  bundle:
    linting: false

functions:
  fetchJobs:
    handler: handler.hello
    events:
      - schedule:
          rate: cron(0 9 * * ? *)
          enabled: true
