# NOTE: update this with your service name
org: designed
app: designedbot-slack
service: designedbot-slack

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  stage: ${opt:stage}
  region: ${env:AWS_REGION}
  name: aws
  runtime: nodejs10.x
  environment:
    WEBHOOK_URL: ${env:WEBHOOK_URL}
    API_URL: ${env:API_URL}

  deploymentPrefix: serverless
  memorySize: 256
  timeout: 30
  logRetentionInDays: 14
  versionFunctions: true

custom:
  bundle:
    linting: false

functions:
  fetchJobs:
    handler: handler.hello
    events:
      - schedule:
          rate: cron(40 * * * ? *)
          enabled: true
