# NOTE: update this with your service name
org: designed
app: designedbot-slack
service: designedbot-slack

# Create an optimized package for our functions 
package:
  individually: true

custom:
  bundle:
    linting: false
  api_urls:
    production: ${env:PROD_API_URL}
    staging: ${env:STAGGING_API_URL}
  webhook_urls:
    production: ${env:PROD_WEBHOOK_URL}
    staging: ${env:STAGGING_WEBHOOK_URL}


plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  stage: ${opt:stage}
  region: ${env:AWS_REGION}
  name: aws
  runtime: nodejs10.x
  environment:
    WEBHOOK_URL: ${self:custom.webhook_urls.${opt:stage}}
    API_URL: ${self:custom.api_urls.${opt:stage}}

  deploymentPrefix: serverless
  memorySize: 256
  timeout: 30
  logRetentionInDays: 14
  versionFunctions: true



functions:
  fetchJobs:
    handler: handler.hello
    events:
      - schedule:
          rate: cron(40 * * * ? *)
          enabled: true

